# Generated by Django 5.0.7 on 2024-07-10 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='blog_description',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='blog_image',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='blog_name',
        ),
    ]
