# Generated by Django 5.0.7 on 2024-07-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_rename_content_blog_blog_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date_created',
        ),
    ]
